name: Build G-Helper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore GHelper/GHelper.csproj

      - name: Build project
        run: dotnet build GHelper/GHelper.csproj --configuration Release

      - name: Publish project
        run: dotnet publish GHelper/GHelper.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: g-helper
          path: ./publish
